# Generated by Django 6.0.1 on 2026-01-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='enlace_boleta',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
