"""Initial migration.

Revision ID: 49098baa70e8
Revises: 
Create Date: 2025-11-10 21:05:13.337228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49098baa70e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generos')
    # ### end Alembic commands ###
