# Generated by Django 5.2.8 on 2025-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150)),
                ('medio', models.CharField(max_length=25)),
                ('fecha_agenda', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('contacto_nombre', models.CharField(max_length=150)),
                ('contacto_telefono', models.CharField(max_length=25)),
                ('contacto_cargo', models.CharField(max_length=45)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
