"""Initial migration.

Revision ID: 386f451c2ca5
Revises: 
Create Date: 2025-11-24 22:20:54.289858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386f451c2ca5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('tipo', sa.String(length=1), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('movimientos')
    # ### end Alembic commands ###
