# Generated by Django 5.2.8 on 2025-12-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='medio',
            field=models.CharField(choices=[('L', 'Llamada'), ('V', 'Videollamada'), ('P', 'Presencial'), ('C', 'Correo')], max_length=25),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_cargo',
            field=models.CharField(choices=[('Jefe de Sucursal', 'Jefe de Sucursal'), ('Jefe de Taller', 'Jefe de Taller'), ('Jefe de Compras', 'Jefe de Compras'), ('Asistente de Compras', 'Asistente de Compras'), ('Asesor de Servicio', 'Asesor de Servicio')], max_length=45),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='servicio',
            field=models.CharField(choices=[('Marketing y ventas', 'Marketing y ventas'), ('Tecnología', 'Tecnología'), ('Finaciero', 'Finaciero'), ('Operativo y Logística', 'Operativo y Logística'), ('Mantenimiento y Postventa', 'Mantenimiento y Postventa')], max_length=100),
        ),
    ]
