CREATE TABLE doctores (
  id SERIAL PRIMARY KEY,
  nombre VARCHAR(150),
  especialidad VARCHAR(150),
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pacientes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(150),
  correo VARCHAR(150),
  telefono VARCHAR(20),
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE citas (
  id SERIAL PRIMARY KEY,
  doctor_id INTEGER NOT NULL,
  paciente_id INTEGER NOT NULL,
  fecha_cita TIMESTAMP,
  estado CHAR(1) DEFAULT 'P',
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "citas" ADD FOREIGN KEY ("doctor_id") REFERENCES "doctores" ("id") ON DELETE CASCADE;
ALTER TABLE "citas" ADD FOREIGN KEY ("paciente_id") REFERENCES "pacientes" ("id") ON DELETE CASCADE;

INSERT INTO pacientes (nombre, correo, telefono) VALUES 
('Ana Gomez', 'ana.gomez@mail.com', '555-1234'),
('Luis Ramirez', 'luis.ramirez@mail.com', '555-4567'),
('Karen Mendoza', 'karen.mendoza@mail.com', '333-1234');

INSERT INTO doctores (nombre, especialidad) VALUES 
('Dra Carmen Lopez', 'Cardiología'),
('Sr Juan Morales', 'Dermatología'),
('Karen Mendoza', 'Medicina General');

INSERT INTO citas (paciente_id, doctor_id, fecha_cita) VALUES 
(1, 3, '2025-10-30'),
(2, 1, '2025-10-31'),
(3, 2, '2025-10-30'),
(1, 2, '2025-10-31'),
(3, 2, '2025-10-31');

SELECT * FROM citas;
SELECT * FROM pacientes;
SELECT * FROM doctores WHERE especialidad='Medicina General';
UPDATE citas SET fecha_cita='2025-11-01' WHERE id=3;
SELECT * FROM citas;
--DELETE FROM pacientes WHERE id=3;
--DELETE FROM citas WHERE id=1;
-- Consultamos los campos nombre del paciente y del doctor
-- Asignamos un alias para el nombre del paciente y del doctor: paciente  y doctor
-- Aplicamos alias para todas la tablas
-- Implementamos INNER JOIN para obtener el registro de los doctores que coincidan con el valor del campo doctor_id
-- Implementamos INNER JOIN para obtener el registro de los pacientes que coincidan con el valor del campo paciente_id
SELECT p.nombre AS paciente, d.nombre AS doctor, fecha_cita, estado
FROM citas c
INNER JOIN doctores d ON d.id=c.doctor_id
INNER JOIN pacientes p ON p.id=c.paciente_id;