CREATE TABLE "eventos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha" date,
  "hora" time,
  "lugar" varchar
);

CREATE TABLE "entradas" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "zona" varchar,
  "precio" decimal(7,2),
  "evento_id" integer NOT NULL
);

CREATE TABLE "generos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar
);

CREATE TABLE "grupos" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar,
  "genero_id" integer NOT NULL
);

CREATE TABLE "evento_grupos" (
  "evento_id" integer NOT NULL,
  "grupo_id" integer NOT NULL
);

ALTER TABLE "entradas" ADD FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");

ALTER TABLE "grupos" ADD FOREIGN KEY ("genero_id") REFERENCES "generos" ("id");

ALTER TABLE "evento_grupos" ADD FOREIGN KEY ("evento_id") REFERENCES "eventos" ("id");

ALTER TABLE "evento_grupos" ADD FOREIGN KEY ("grupo_id") REFERENCES "grupos" ("id");
