# Generated by Django 5.2.8 on 2025-12-05 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_agenda_descripcion_alter_agenda_medio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='activo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
