# Generated by Django 5.2.8 on 2025-12-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_agenda_activo_alter_agenda_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1),
        ),
    ]
