"""adicionar columna role a usuarios

Revision ID: 66af5a94d980
Revises: 0222af3dfdf8
Create Date: 2025-11-26 20:54:49.630285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66af5a94d980'
down_revision = '0222af3dfdf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
