"""Se agrega el modelo Libro

Revision ID: 4bcf7ea22fb5
Revises: 7476ee65f1f8
Create Date: 2025-11-10 22:26:33.706591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcf7ea22fb5'
down_revision = '7476ee65f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.Column('editorial_id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=25), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('anio', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autores.id'], ),
    sa.ForeignKeyConstraint(['editorial_id'], ['editoriales.id'], ),
    sa.ForeignKeyConstraint(['genero_id'], ['generos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('libros')
    # ### end Alembic commands ###
