"""Se actualizan los modelos Genero, Editorial y Autor

Revision ID: 7476ee65f1f8
Revises: 49098baa70e8
Create Date: 2025-11-10 22:03:32.021753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7476ee65f1f8'
down_revision = '49098baa70e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=150), nullable=False),
    sa.Column('nacionalidad', sa.String(length=100), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('editoriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_registro', sa.DateTime(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generos', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('fecha_registro')

    op.drop_table('editoriales')
    op.drop_table('autores')
    # ### end Alembic commands ###
