dato1 = None    # Null
dato2 = 2       # Entero
dato3 = 1.3     # Decimal
dato4 = False   # Booleano
dato5 = "texto" # Cadena de texto
dato6 = 3 + 4j  # Complejo
dato7 = (1,3,3) # Tupla
dato8 = [1,2,3] # Lista
dato9 = {1,2}   # Set (Conjunto)
dato10= {"1":"A","2":"B"}   # Diccionario